kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/Karnatiswetcha/example

steps:
  - name: test
    image: node
    commands:
      - npm install
#      - npm test

  - name: build
    image: node
    commands:
      - npm build

  - name: deploy
    image: robertstettner/drone-cloudformation
    stackname: my-awesome-stack
    template: templates/stack.yml
    params:
      Version: 123
      Environment: staging
#    when:
#      event: deployment

#  - name: run
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#      - ./output


#volumes:
#  - name: reports
#    host:
#      path: /home/dev/work/src/github.com/cyantarek/drone-go-git-test/reports