AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: arn:aws:iam::094888303235:role/service-role/test-role-5mevfe03
      Handler: index.handler
      Code:
        ZipFile: |
          console.log("hello world here I am")

      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active